name: CI

on:
  push:
    branches: [ main ]

env:
  FLUTTER_VERSION: 3.22.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build Flutter web
        run: flutter build web --release

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/web/

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download production artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/web/

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}